module.exports = {
  item: require("./item"),
  list: require("./list"),
  popup: require("./popup"),
  droplist: require("./droplist"),
  actionlist: require("./actionlist"),
  hoverable: require("./hoverable"),
  sorter: require("./sorter"),
  tooltip: require("./tooltip"),
  mininote: require("./mininote"),
  miniWindow: require("./miniWindow"),
  toggler: require("./toggler"),
  touchableOpacity: require("./touchableOpacity"),
  pricable: require("./pricable"),
  hover: require("./hover"),
  click: require("./click"),
  clicked: require("./clicked"),
  touch: require("./touch"),
  loaded: require("./loaded"),
  contentful: require("../function/contentful").contentful
}